#!/usr/bin/python
#
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

GCS_PREFIX = 'gs://'
# Vertex is only in us-central1 for now.
LOCATION = 'us-central1'
# Endpoint ID of the embeddings endpoint
ENDPOINT_ID = 6695981832690728960
# GCP project ID of the embeddings endpoint
EMBEDDINGS_PROJECT_ID = 'gh-rad-validation-cxrembd-deid'

# tf.Example feature keys required by the embeddings service
IMAGE_KEY = 'image/encoded'
IMAGE_FORMAT_KEY = 'image/format'

# Key for this library to serialize generated embeddings
EMBEDDING_KEY = 'embedding'

# The size of the float vector embeddings generated by the CXR foundation API
DEFAULT_EMBEDDINGS_SIZE = 1376
